"""Schema v0: models, vocabularies, issue types and the JSON Schema export."""

from __future__ import annotations

from rail_vision_bench import SCHEMA_VERSION
from rail_vision_bench.schema.issues import (
    STRICT_PROMOTED,
    WARNING_CODES,
    IssueCode,
    Severity,
    ValidationIssue,
    ValidationReport,
)
from rail_vision_bench.schema.models import (
    Confidence,
    Derailer,
    DerailerPosition,
    DerailerState,
    Direction,
    EdgeAttachment,
    ElementId,
    Geometry,
    Node,
    NodeKind,
    Occupancy,
    Port,
    PortPath,
    PortRef,
    Provenance,
    ProvenanceKind,
    Route,
    RouteState,
    RouteStatus,
    SceneAnnotation,
    Signal,
    SignalAspect,
    SignalKind,
    SignalState,
    Source,
    SourceKind,
    State,
    SwitchPosition,
    SwitchState,
    Topology,
    Track,
    TrackKind,
    TrackState,
)

__all__ = [
    "SCHEMA_VERSION",
    "STRICT_PROMOTED",
    "WARNING_CODES",
    "Confidence",
    "Derailer",
    "DerailerPosition",
    "DerailerState",
    "Direction",
    "EdgeAttachment",
    "ElementId",
    "Geometry",
    "IssueCode",
    "Node",
    "NodeKind",
    "Occupancy",
    "Port",
    "PortPath",
    "PortRef",
    "Provenance",
    "ProvenanceKind",
    "Route",
    "RouteState",
    "RouteStatus",
    "SceneAnnotation",
    "Severity",
    "Signal",
    "SignalAspect",
    "SignalKind",
    "SignalState",
    "Source",
    "SourceKind",
    "State",
    "SwitchPosition",
    "SwitchState",
    "Topology",
    "Track",
    "TrackKind",
    "TrackState",
    "ValidationIssue",
    "ValidationReport",
]
